"""empty message

Revision ID: 12506e79e6cd
Revises: c41f12037381
Create Date: 2026-02-08 18:54:42.144477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12506e79e6cd'
down_revision = 'c41f12037381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.alter_column('comment_text',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    # ### end Alembic commands ###
