"""empty message

Revision ID: 3e1876b95c0e
Revises: cae6b317bc1a
Create Date: 2026-02-05 23:58:07.551505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1876b95c0e'
down_revision = 'cae6b317bc1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('firstName', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
