"""empty message

Revision ID: 9f4900c1c4c1
Revises: 33aa9500c1b7
Create Date: 2026-02-08 18:21:06.461324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4900c1c4c1'
down_revision = '33aa9500c1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published_post', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('published_post')

    # ### end Alembic commands ###
